version: '2'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - proxy-network
    labels:
      - "traefik.enable=false"

networks:
  proxy-network:
    external:
      name: proxy-network

